# Generated by Django 2.2.7 on 2019-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/blog/')),
            ],
        ),
    ]
